services:
  - type: web
    name: kino-bot-uz
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: MONGO_URL
        sync: false # Optional: Enter MongoDB Atlas connection string here
      - key: BASE_URL
        value: https://example.com/ichkarida
