services:
  - type: web
    name: kino-bot-uz
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: MONGO_URL
        sync: false # Optional: for free MongoDB cloud database
      - key: DATA_DIR
        value: /data # Path to the persistent disk mount point
      - key: BASE_URL
        value: https://example.com/ichkarida
    disk:
      name: kino-db-disk
      mountPath: /data
      sizeGB: 1
